#!/bin/bash
echo "enter name of test"

read testName

mkdir Tests/$testName

echo ------------- Log for $testName ------------- >> Tests/$testName/log.txt

echo Created on `date` >> Tests/$testName/log.txt

mkdir Tests/$testName/components

touch Tests/$testName/main.skp

